services:

  db:
    image: postgres:alpine3.20
    container_name: pgdb_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_dev

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: python_container
    volumes:
      - ./src:/home/code:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db